// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF8xPl3KyGuoUGzLrcbVWdqgC4mQzHxi0',
    appId: '1:126212317099:android:0c75597bb7f64be9f03cee',
    messagingSenderId: '126212317099',
    projectId: 'event-planning-app-43083',
    storageBucket: 'event-planning-app-43083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RHvjjSoINwzrsdzOMVqoyV8t0QYY1Vk',
    appId: '1:126212317099:ios:ac4b5af87de34463f03cee',
    messagingSenderId: '126212317099',
    projectId: 'event-planning-app-43083',
    storageBucket: 'event-planning-app-43083.firebasestorage.app',
    iosBundleId: 'com.example.competeHub',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1VisF7lTvs7Y1ZbU45E8pQNBA0M-vIg',
    appId: '1:126212317099:web:634ffe7a99451f80f03cee',
    messagingSenderId: '126212317099',
    projectId: 'event-planning-app-43083',
    authDomain: 'event-planning-app-43083.firebaseapp.com',
    storageBucket: 'event-planning-app-43083.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf1VisF7lTvs7Y1ZbU45E8pQNBA0M-vIg',
    appId: '1:126212317099:web:84113af2338bb9eaf03cee',
    messagingSenderId: '126212317099',
    projectId: 'event-planning-app-43083',
    authDomain: 'event-planning-app-43083.firebaseapp.com',
    storageBucket: 'event-planning-app-43083.firebasestorage.app',
  );
}
